# Housing Instability: Trends, Risks, and Impacts📝

![Banner](./assets/banner.jpeg)

## Topic
*What problem are you (or your stakeholder) trying to address?*
📝 <!-- Answer Below -->
A problem that I would like to explore this semester is the housing crisis/homelessness that is rampant right now in today's world. Housing insecurity includes unstable housing, overcrowding, frequent moves, and risk of eviction, while homelessness refers to people living in shelters, temporary spaces, or without shelter at all. Rising rents, stagnant wages, and limited affordable housing make this a major challenge in many U.S. cities. It affects health, employment, education, and long‑term stability. It's significant today because rent prices have increased faster than income in many regions and homelessness is rising among families, youth, and older adults.

## Project Question
*What specific question are you seeking to answer with this project?*
*This is not the same as the questions you ask to limit the scope of the project.*
📝 <!-- Answer Below -->
How are rising housing costs and income trends contributing to housing insecurity and homelessness in U.S. cities today?

## What would an answer look like?
*What is your hypothesized answer to your question?*
📝 <!-- Answer Below -->
I expect the data to show that rising housing costs are outpacing income growth in many communities, creating a widening gap between what people earn and what they must pay for rent. As this gap grows, more households become rent‑burdened, which increases their risk of eviction, frequent moves, and ultimately homelessness.

## Data Sources
*What 3 data sources have you identified for this project?*
*How are you going to relate these datasets?*
📝 <!-- Answer Below -->
1. US Homelessness & Housing Data — Kaggle (File Download)  
This dataset integrates HUD Point‑in‑Time homelessness counts with Census ACS indicators at the Continuum of Care (CoC) level. It allows me to directly analyze how changes in economic conditions, housing availability, and demographic factors relate to changes in homelessness over time.

2. Rent as a Percentage of Household Income — Census API  
This ACS table measures rent burden, one of the strongest predictors of housing instability and homelessness. I can compare rent‑burden rates across states, counties, or years, and join this dataset with my Kaggle homelessness dataset using shared geographic identifiers such as state, county FIPS, or CoC crosswalks.

3. Zillow Observed Rent Index (ZORI) — Zillow (File Download)  
ZORI provides monthly and annual trends in median asking rents across U.S. regions. By aligning ZORI with ACS rent‑burden indicators and HUD homelessness counts at the county or state level, I can analyze whether areas experiencing faster rent growth also show higher levels of housing insecurity and homelessness. ZORI offers a clear measure of affordability pressure, helping me examine rising rents as a key driver of housing instability.

## Approach and Analysis
*What is your approach to answering your project question?*
*How will you use the identified data to answer your project question?*
📝 <!-- Start Discussing the project here; you can add as many code cells as you need -->
My approach to answering the project question is to combine homelessness counts, eviction activity, and housing‑cost indicators to understand how economic pressures contribute to housing insecurity over time. I will begin by exploring each dataset individually to understand trends in homelessness, rent burden, and eviction filings. I will also look for correlations, patterns, and trends across the 17‑year period to determine whether rising housing costs and increased eviction risk are associated with increases in homelessness. This combined approach allows me to evaluate not only the scale of homelessness but also the underlying economic and housing conditions that may be driving it.

In [1]:
# Start your code here
import zipfile

with zipfile.ZipFile("Homeless.zip", "r") as z:
    z.extractall("data")

In [2]:
import pandas as pd

df = pd.read_csv("data/Final_National_Dataset.csv")
df.head()

,CoC_Code,CoC_Name,Homeless_Count,Sheltered_Count,Unsheltered_Count,Year,State,Area_Name,Total_Pop,Poverty_Count,...,Vacant_Units_MOE,Total_Housing_Units_MOE,Rent_Burden_30_35_MOE,Rent_Burden_35_40_MOE,Rent_Burden_40_50_MOE,Rent_Burden_50_Plus_MOE,Poverty_Rate,Unemployment_Rate,Vacancy_Rate,Rent_Burden_Rate
0,AK-500,Anchorage CoC,1494.0,1369.0,125.0,2022,AK,Anchorage,290674,27415.0,...,876.000000,166.000000,461.000000,530.000000,519.000000,752.000000,0.094315,0.026652,0.099245,0.060253
1,AK-501,Alaska Balance of State CoC,826.0,594.0,232.0,2022,AK,Alaska Balance of State,434533,47184.0,...,980.497833,836.246375,452.829990,363.301528,486.370229,661.561033,0.108586,0.034239,0.236550,0.042805
2,AL-500,"Birmingham/Jefferson, St. Clair, Shelby Counti...",943.0,601.0,342.0,2022,AL,"Birmingham/Jefferson, St. Clair, Shelby Counties",987900,128760.0,...,1847.515359,192.720004,976.406678,727.407726,966.004658,1426.055399,0.130337,0.023553,0.120973,0.055373
3,AL-501,Mobile City & County/Baldwin County CoC,585.0,388.0,197.0,2022,AL,Mobile City & County/Baldwin County,647298,94798.0,...,1774.919153,141.400141,908.240056,742.081532,872.708428,1250.908470,0.146452,0.022969,0.192126,0.056411
4,AL-502,Florence/Northwest Alabama CoC,232.0,198.0,34.0,2022,AL,Florence/Northwest Alabama,269584,40538.0,...,1087.420802,104.498804,489.277018,277.245379,388.307868,555.018018,0.150372,0.017605,0.179779,0.036890

In [10]:
df = pd.read_csv("data/Census.csv")
df.head()

,Label (Grouping),United States!!Estimate,United States!!Margin of Error
0,Total:,"46,101,640","±154,221"
1,Less than 10.0 percent,"1,650,115","±26,645"
2,10.0 to 14.9 percent,"3,532,220","±39,851"
3,15.0 to 19.9 percent,"5,152,781","±44,866"
4,20.0 to 24.9 percent,"5,412,134","±50,270"

In [11]:
df = pd.read_csv("data/Zillow.csv")
df.head()

,RegionID,SizeRank,RegionName,RegionType,StateName,2015-01-31,2015-02-28,2015-03-31,2015-04-30,2015-05-31,...,2025-04-30,2025-05-31,2025-06-30,2025-07-31,2025-08-31,2025-09-30,2025-10-31,2025-11-30,2025-12-31,2026-01-31
0,102001,0,United States,country,NaN,1136.875660,1143.091571,1151.628492,1160.334639,1168.937100,...,1891.718540,1900.093803,1905.555874,1907.970919,1908.425577,1906.815052,1903.136022,1897.457476,1893.079810,1894.812508
1,394913,1,"New York, NY",msa,NY,2147.623068,2162.038487,2180.440072,2198.666017,2212.859042,...,3175.002413,3202.184453,3232.903750,3261.988647,3282.402140,3279.629635,3266.917419,3246.041279,3234.192899,3232.316444
2,753899,2,"Los Angeles, CA",msa,CA,1745.689589,1756.971610,1772.234004,1787.247740,1801.898197,...,2887.746640,2892.553080,2897.174510,2900.108469,2901.111619,2900.674280,2897.770375,2890.957145,2881.996091,2884.813189
3,394463,3,"Chicago, IL",msa,IL,1343.902521,1350.949124,1360.799161,1369.910884,1379.609447,...,2042.403060,2061.841565,2079.868003,2090.749547,2094.633714,2092.993114,2087.380071,2082.309385,2080.267683,2091.226250
4,394514,4,"Dallas, TX",msa,TX,1045.936211,1050.668328,1058.120800,1069.218528,1078.410916,...,1659.405853,1663.923737,1665.448891,1662.221097,1658.261579,1653.220900,1646.828823,1640.644284,1635.001553,1632.977977

## Resources and References
*What resources and references have you used for this project?*
📝 <!-- Answer Below -->
I used kaggle and Census API datasets

In [ ]:
# ⚠️ Make sure you run this cell at the end of your notebook before every submission!
!jupyter nbconvert --to python source.ipynb

[NbConvertApp] Converting notebook source.ipynb to python
[NbConvertApp] Writing 1271 bytes to source.py